name: Build & Release

on:
  push:
    branches:
      - '!*'
      - 'main'
    tags:
      - 'v*.*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_type }}
  cancel-in-progress: true

env:
  IsTag: ${{ startsWith(github.ref, 'refs/tags/v') && 'true' || '' }}

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-deps
      - run: npm run build
      - run: npm run package
      - run: npm run manifest

      - name: Retrieve commit URL
        if: ${{ !env.IsTag }}
        id: commit-url
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: echo "value=$(gh browse ${{ github.sha}} -n)" >> $GITHUB_OUTPUT

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          name: ${{ env.IsTag && format('Release {0}', github.ref_name) || 'Upcoming Release' }}
          body: ${{ !env.IsTag && format('Built from [this commit]({1}).', github.sha, steps.commit-url.outputs.value) || '' }}
          prerelease: ${{ !env.IsTag }}
          commit: main
          tag: ${{ env.IsTag && github.ref_name || 'pre-release' }}
          generateReleaseNotes: true
          allowUpdates: true
          updateOnlyUnreleased: true
          artifacts: '*.ipk,*.manifest.json'
